#차원 교재 실습

In [7]:
vector = np.array([1, 2, 3])  # 원본 벡터
print("vector:", vector)
print("vector.ndim:", vector.ndim)
print("---------")

column_vector = vector[:, np.newaxis]  # 전체 원소를 세로 방향으로 확장
print("column_vector:\n", column_vector)
print("column_vector.ndim:", column_vector.ndim)
print("---------")

first_element_column = vector[0, np.newaxis]  # 첫 번째 원소만 세로 방향으로 확장

print("first_element_column:\n", first_element_column)
print("first_element_column.ndim:", first_element_column.ndim)
print("---------")

range_column_vector = vector[1:3, np.newaxis]  # 1(두번째 요소), 3(네 번째 요소 바로 전 요소) 범위를 세로 방향으로 확장
print("range_column_vector:\n", range_column_vector)
print("range_column_vector.ndim:", range_column_vector.ndim)

vector: [1 2 3]
vector.ndim: 1
---------
column_vector:
 [[1]
 [2]
 [3]]
column_vector.ndim: 2
---------
first_element_column:
 [1]
first_element_column.ndim: 1
---------
range_column_vector:
 [[2]
 [3]]
range_column_vector.ndim: 2


#차원 미니퀘스트

##1번 퀘스트
👉 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

In [2]:
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in array:
  print(i.ndim)

2
2


##2번 퀘스트
1차원 배열 [10, 20, 30, 40, 50, 60]을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)
print(arr.reshape(2,3))

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


##3번 퀘스트

👉 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.

- `newaxis`를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.

```python
import numpy as np
array = np.array([7, 14, 21])
```

In [8]:
array = np.array([7, 14, 21])
print(array[:, np.newaxis])
print(array[:, np.newaxis].ndim)

[[ 7]
 [14]
 [21]]
2


#Shape 교재 실습



*   ndim (축의 개수) <-> shape (차원별 요소 개수)

*   array.resize() : 형태 변경, 부족산 부분은 0으로 채워짐

*   array.transpose() : 배열 축 전환

---

*   array.flatten() : 다차원을 1차원으로 (새로운 배열 생성)

*  array.revel() : 다차원을 1차원으로 (원본 내열 변경)



#Shape 미니퀘스트

##1번 퀘스트

👉 주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
```

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


### 2번 퀘스트

👉 1차원 배열 `[10, 20, 30, 40, 50, 60]`을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

In [10]:
array = np.array([10,20,30,40,50,60])

new_array = array.reshape(2,3)

print(new_array)

[[10 20 30]
 [40 50 60]]


### 3번 퀘스트

👉 다음 1차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.

```
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
```

In [11]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#(3,2,2)
#[[]1,2],[3,4]] [[5,6],[7,8]] [[9,10],[11,12]]
print(array.reshape(3,2,2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#데이터 타입 교재 실습



*   array.dtype : 데이터 타입 확인 <br>
(+) 배열을 생성할 때 인수를 사용해서 데이터 타입을 명시적으로 지정 가능
*   array.itemsize
*   array.nbyte
*   array.astype(np.변환하고자하는타입) : 데이터 타입 변경




#데이터타입 미니퀘스트

### 1번 퀘스트

👉 아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([10, 20, 30])
```

In [12]:
array = np.array([10, 20, 30])
print(array.dtype)

int64


### 2번 퀘스트


👉 정수형 배열 `[1, 2, 3]`을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

In [16]:
array = np.array([1,2,3])
print("before:", array.dtype)

new_array = array.astype(np.float64)
print("after: ", new_array.dtype)

before: int64
after:  float64


### 3번 퀘스트

👉 NumPy 배열 `[100, 200, 300]`을 `uint8`로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

In [17]:
#uint8 : 부호 없는 정수 데이터 타입

array = np.array([100, 200, 300])
print("before: ", array.dtype, array.nbytes)

new_array = array.astype(np.uint8)
print("after: ", new_array.dtype, new_array.nbytes)

before:  int64 24
after:  uint8 3


#인덱싱 교재 실습



*   array[index] : 해당 index에 있는 요소 출력
*   array[row, col] : 정수 인덱싱
*   array[start:end:step] : 슬라이싱
*   array[조건식] : 불리언 인덱싱
*   array[[i1, i2 ..]] : 팬시 인덱싱 (특정 인덱스 선택)
<br>

*   [참고] np.where(요소) : 해당 요소의 index 확인


#인덱싱 미니퀘스트

### 1번 퀘스트

<aside>
👉 주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([10, 20, 30, 40, 50])
```

</aside>

In [19]:
array = np.array([10, 20, 30, 40, 50])

for i in array:
  print(i)

10
20
30
40
50


### 2번 퀘스트

<aside>
👉 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

```python
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

</aside>

In [30]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

#첫 번째 열
1,4,7
for i in range(len(matrix)):
  print(matrix[i][0])
  # 위와 동일하다 : print(matrix[i,0])


#두 번째 행
4,5,6
print(matrix[1:2])

1
4
7
[[4 5 6]]


### 3번 퀘스트

<aside>
👉 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])
```

</aside>

In [49]:
array = np.array([5, 15, 8, 20, 3, 12])

print("주어진 배열 중 10보다 큰 요소 출력:", array[array>10])

print("주어진 배열 중 10보다 큰 요소의 index 출력:", np.where(array > 10))

주어진 배열 중 10보다 큰 요소 출력: [15 20 12]
주어진 배열 중 10보다 큰 요소의 index 출력: (array([1, 3, 5]),)


#연산 교재 실습



*   np.add(), np.abstract()
*   np.equal(), np.greater()
*  np.logical_and(), np.logical_or()
*   np.mean(), np.sum(), np.max()
*   np.dot()
<br>

*   행을 axis = 1 / 열은 axis = 0



#연산 미니퀘스트

### 1번 퀘스트

<aside>
👉 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

```python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

</aside>

In [53]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

for i in range(len(a)):
  print(a[i] + b[i])

5
7
9


### 2번 퀘스트

<aside>
👉 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 `[1, 2, 3]`을 더하는 코드를 작성하세요.

```python
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
```

</aside>

In [54]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

print(matrix + vector)

[[11 22 33]
 [41 52 63]]


### 3번 퀘스트

<aside>
👉 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
```

</aside>

In [71]:
array = np.array([[3, 7, 2], [8, 4, 6]])
arr = []

#행 axis의 최댓값
for i in range(len(array)):
  a = np.max(array[i])
  arr = np.append(arr, a)
print(f"{arr}는 {arr.ndim}차원이다")
#[참고] 행의 최댓값은 np.max(array, axis=1)로 할 수 있다


#열 axis의 최댓값
result = np.max(array, axis=0)
print(f"{result}는 {result.ndim}차원이다")

[7. 8.]는 1차원이다
[8 7 6]는 1차원이다


#유니버설 함수 교재 실습



🤖 numpy에서 연산과 유니버설함수 <br>
1. 기본 연산 : 내부적으로 유니버설 함수를 호출하여 브로드캐스팅과 요소별 연산을 수행
-> 여러 배열을 한 번에 연산하려면 중간에 임시 배열(메모리)이 생성되어 비효율적일 수 있다.

2. 유니버설 함수 :

*   지정인자 : 계산 결과를 다른 메모리에 새로 만들지 않고 기존 배열에 바로 덮어쓸 수 있다.
*   축 지정 : 특정 차원을 기준으로 한 번에 연산 가능



---

*   array 에 추가하는 방법은 append <br> np.append(추가하려는 배열, 추가하려는 요소)



#유니버설 함수 미니퀘스트

### 1번 퀘스트

<aside>
👉 배열 `[1, 2, 3, 4]`에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요.

</aside>

In [74]:
array = np.array([1,2,3,4])
a = 0

for i in array:
  a += np.power(i,2)
  print(a)

print("total:", a)

1
5
14
30
total: 30


### 2번 퀘스트

<aside>
👉 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

```python
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
```

</aside>

In [79]:
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

for i in range(len(array1)):
  a = np.add(array1[i], array2[i])
  print(a)
  array1 = np.append(array1, a)

print(f"array1에 요소별 합을 저장하면: {array1}")

11
22
33
array1에 요소별 합을 저장하면: [10 20 30 11 22 33]


### 3번 퀘스트

<aside>
👉 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(`log 값 > 1`)을 만족하는 요소만 출력하는 코드를 작성하세요.

```python
array = np.array([1, np.e, 10, 100])
```

</aside>

In [83]:
array = np.array([1, np.e, 10, 100])
new_array = np.log(array)

print(f"모든 요소에 자연로그를 한 결과는: {new_array}")

print(f"특정 조건을 만족하는 요소는: {new_array[new_array>1]}")


모든 요소에 자연로그를 한 결과는: [0.         1.         2.30258509 4.60517019]
특정 조건을 만족하는 요소는: [2.30258509 4.60517019]
